
version: "3.4"
networks:
  net:
    driver: overlay
    attachable: true
services:
  www:
    image: node:20.8.1
    working_dir: /app
    command: >
      sh -c "npm install && npm run serve"
    volumes:
      - ${PWD}/apps:/app